Project4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('story4.urls'), name='homepage'),
    path('schedule/', include('story5.urls'), name='schedule'),
    path('activity/', include('story6.urls'), name='activity'),
]

story4/urls.py
from django.urls import path
from . import views

app_name = 'story4'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('profile/', views.profile, name='profile'),
    path('gallery/', views.gallery, name='gallery'),
    path('debut-story/', views.debut_story, name='debut_story'),
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.schedule, name='schedule'),
    path('add/', views.add, name='add'),
    path('delete/<str:pk>', views.deleteItem, name='delete'),
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.activity, name='activity'),
    path('delete/<str:pk>', views.delete, name='activityDelete')
]

story4/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

# Create your models here.

class Course(models.Model):
    TERM_CHOICES = [
        ('Ganjil', 'Ganjil'),
        ('Genap', 'Genap')
    ]
    YEAR_CHOICES = [
        ('2019/2020', '2019/2020'),
        ('2020/2021', '2020/2021'),
        ('2021/2022', '2021/2022'),
        ('2022/2023', '2022/2023'),
    ]
    name = models.CharField(max_length=50)
    teacher = models.CharField(max_length=100)
    sks = models.PositiveIntegerField()
    term = models.CharField(
        max_length=6,
        choices=TERM_CHOICES,
        default='Ganjil'
    )
    year = models.CharField(
        max_length=9,
        choices=YEAR_CHOICES,
        default='2019/2020'
    )
    room = models.CharField(max_length=20)
    desc = models.CharField(max_length=300)

    def __str__(self):
        return self.name

story6/models.py
from django.db import models

# Create your models here.

class Activity(models.Model):
    activity = models.CharField(max_length=100)
    def __str__(self):
        return self.activity

class Member(models.Model):
    member = models.CharField(max_length=100)
    kegiatan = models.ForeignKey(Activity, on_delete=models.CASCADE)
    def __str__(self):
        return self.member

story5/forms.py
from django import forms
from .models import Course

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'teacher', 'sks', 'term', 'year', 'room', 'desc']
        widgets = {
            'name' : forms.TextInput(attrs={'class':'form-control'}),
            'teacher' : forms.TextInput(attrs={'class':'form-control'}),
            'sks' : forms.NumberInput(attrs={'class':'form-control'}),
            'term' : forms.Select(attrs={'class':'form-control'}),
            'year' : forms.Select(attrs={'class':'form-control'}),
            'room' : forms.TextInput(attrs={'class':'form-control'}),
            'desc' : forms.TextInput(attrs={'class':'form-control'}),
        }

story6/forms.py
from django import forms
from .models import Activity, Member

class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = '__all__'
        widgets = {
            'activity' : forms.TextInput(attrs={
                'class' : 'form-control',
                'placeholder' : "What are you up to?"}),
            }

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = '__all__'
        widgets = {
            'member' : forms.TextInput(attrs={
                'class' : 'form-control',
                'placeholder' : "Wanna participate?"}),
        }

story4/views.py
from django.shortcuts import render

# Create your views here.
def homepage(request):
    return render(request, 'story4/index.html')

def profile(request):
    return render(request, 'story4/profile.html')

def gallery(request):
    return render(request, 'story4/gallery.html')

def debut_story(request):
    return render(request, 'story4/story1.html')

story5/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Course
from .forms import CourseForm

# Create your views here.

def schedule(request):
    courses = Course.objects.all()
    context = {'courses' : courses}
    return render(request, 'story5/index.html', context)

def add(request):
    form = CourseForm()
    if request.method == "POST":
        form = CourseForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, (f"The course \"{request.POST['name']}\" has been successfully added to the list!"))
            return redirect('story5:schedule')
        else:
            messages.warning(request, ("The data you entered didn't match the criteria!"))
            return redirect('story5:add')
    context = {'form' : form}
    return render(request, 'story5/add.html', context)

def deleteItem(request, pk):
    course = Course.objects.get(id=pk)
    course.delete()
    messages.success(request, (f"The course \"{course}\" has been removed from the list."))
    return redirect('story5:schedule')

story6/views.py
from django.shortcuts import render, redirect
from .models import Member, Activity
from .forms import MemberForm, ActivityForm
from django.contrib import messages

# Create your views here.

def activity(request):
    if request.method == "POST":
        activityForm = ActivityForm(request.POST)
        memberForm = MemberForm(request.POST)
        if activityForm.is_valid():
            activityForm.save()
            messages.success(request, (f"The activity \"{request.POST['activity']}\" has been successfully added!"))
            return redirect('story6:activity')
        elif memberForm.is_valid():
            memberForm.save()
            messages.success(request, (f"{request.POST['member']} successfully joined as a member!"))
            return redirect('story6:activity')
        else:
            messages.warning(request, (f"Incorrect input!"))
            return redirect('story6:activity')

    else:
        activityForm = ActivityForm()
        memberForm = MemberForm()
        activities = Activity.objects.all()
        members = Member.objects.all()
        context = {
            'activityForm' : activityForm,
            'memberForm' : memberForm,
            'activities' : activities,
            'members' : members
        }
        return render(request, 'story6/index.html', context)

def delete(request, pk):
    activity = Activity.objects.get(id=pk)
    activity.delete()
    messages.warning(request, (f"The activity \"{activity}\" has been successfully deleted!"))
    return redirect('story6:activity')

templates/base.html
<!DOCTYPE html>
{% load static %}

{% url 'story4:homepage' as homepage_url %}
{% url 'story4:profile' as profile_url %}
{% url 'story4:gallery' as gallery_url %}
{% url 'story4:debut_story' as debut_story_url %}
{% url 'story5:schedule' as schedule_url %}
{% url 'story5:add' as add_url %}
{% url 'story6:activity' as activity_url %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Montserrat for Story 4 -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <!-- Nanum Gothic for Story 1 -->
    <link href="https://fonts.googleapis.com/css?family=Nanum Gothic" rel="stylesheet">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- Font Awesome for star icons in [page: profile, section: skills] -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- jQuery for collapsible navbar -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Customizable CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'design.css' %}">

    <title>{% block title %}{% endblock title %}</title>
</head>

{% if request.path == debut_story_url %}
<body class="debut">
{% else %}
<body class="d-flex flex-column">
{% endif %}
    {% include 'navbar.html' %}
    <div class="content">
        {% block content %}
        {% endblock content %}
    </div>
    {% include 'footer.html' %}
</body>

</html>

templates/footer.html
{% load static %}

<div class="medsos container" id="medsos">
    <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-3 col-3">
            <a href="https://www.linkedin.com/in/anthonymrtn/">
                <img src="{% static '010-linkedin.png' %}" alt="LinkedIn Icon">
            </a>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-3">
            <a href="https://www.instagram.com/anthonymrtn/">
                <img src="{% static '011-instagram.png' %}" alt="Instagram Icon">
            </a>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-3">
            <a href="https://www.facebook.com/msimanjuntak92">
                <img src="{% static '001-facebook.png' %}" alt="Facebook Icon">
            </a>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-3">
            <a href="https://twitter.com/anthonymartout">
                <img src="{% static '002-twitter.png' %}" alt="Twitter Icon">
            </a>
        </div>
    </div>
</div>
<br><br><br>
<footer id="sticky-footer" class="py-1">
    <div class="container text-center">
        <p>© 2020 MARTOUT INC. All Rights Reserved.</p>
    </div>
</footer>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-md navbar-custom">
    <a class="navbar-brand" href="{{ homepage_url }}"><img class="d-inline-block align-top" src="{% static 'LOGO-WEBSITE.png' %}" alt="Logo" height="40px" width="40px"><span class="website-name">MARTOUT</span></a>
    <button class="navbar-toggler navbar-light" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link {% if request.path == homepage_url %} active {% endif %}" href="{{ homepage_url }}">
                    HOME
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.path == profile_url %} active {% endif %}" href="{{ profile_url }}">
                    PROFILE
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.path == gallery_url %} active {% endif %}" href="{{ gallery_url }}">
                    GALLERY
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.path == debut_story_url %} active {% endif %}" href="{{ debut_story_url }}">
                    STORY 1
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.path == schedule_url %} active {% endif %}" href="{{ schedule_url }}">
                    COURSES
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.path == activity_url %} active {% endif %}" href="{{ activity_url }}">
                    ACTIVITIES
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#medsos">
                    SOCIAL
                </a>
            </li>
        </ul> 
    </div>
</nav>
<br><br>

templates/story4/gallery.html
{% extends "base.html" %}
{% load static %}
{% block title %}Gallery - MARTOUT{% endblock title %}

{% block content %}
<div class="section top container">
    <div class="row">
        <div class="col">
            <h1 class="title">GALLERY</h1>
        </div>
    </div>
</div>
<br><br>
<div class="collage container">
    <div class="row">
        <div class="gallery-image col-sm">
            <img class="image__img" src="{% static 'bicester village.jpg' %}" alt="Bicester Village">
            <div class="image__overlay">
                <div class="image__title">Bicester Village</div>
                <p class="image__description">
                    January 20, 2019
                </p>
            </div>
        </div>
        <div class="gallery-image col-sm">
            <img class="image__img" src="{% static 'lokatara festival.jpg' %}" alt="Lokatara Festival">
            <div class="image__overlay">
                <div class="image__title">Lokatara Festival</div>
                <p class="image__description">
                    November 23, 2018
                </p>
            </div>
        </div>
        <div class="gallery-image col-sm">
            <img class="image__img" src="{% static 'vauxhall.jpg' %}" alt="Vauxhall">
            <div class="image__overlay">
                <div class="image__title">Vauxhall</div>
                <p class="image__description">
                    January 20, 2019
                </p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="gallery-image col-sm">
            <img class="image__img" src="{% static 'liverpool.jpg' %}" alt="Liverpool Lime Street">
            <div class="image__overlay">
                <div class="image__title">Liverpool Lime Street</div>
                <p class="image__description">
                    January 24, 2019
                </p>
            </div>
        </div>
        <div class="gallery-image col-sm">
            <img class="image__img" src="{% static 'hyde park.jpg' %}" alt="Hyde Park">
            <div class="image__overlay">
                <div class="image__title">Hyde Park</div>
                <p class="image__description">
                    January 21, 2019
                </p>
            </div>
        </div>
        <div class="gallery-image col-sm">
            <img class="image__img" src="{% static 'loki-the-golden.jpg' %}" alt="Loki the Golden">
            <div class="image__overlay">
                <div class="image__title">Loki the Golden</div>
                <p class="image__description">
                    August 21, 2020
                </p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="gallery-image col-sm">
            <img class="image__img" src="{% static 'bengkulu.jpg' %}" alt="Bengkulu">
            <div class="image__overlay">
                <div class="image__title">Bengkulu</div>
                <p class="image__description">
                    January 16, 2020
                </p>
            </div>
        </div>
        <div class="gallery-image col-sm">
            <img class="image__img" src="{% static 'laterns-gapfohl.jpg' %}" alt="Laterns-Gapfohl">
            <div class="image__overlay">
                <div class="image__title">Laterns-Gapfohl</div>
                <p class="image__description">
                    January 29, 2019
                </p>
            </div>
        </div>
        <div class="gallery-image col-sm">
            <img class="image__img" src="{% static 'holyrood palace.jpg' %}" alt="Holyrood Abbey">
            <div class="image__overlay">
                <div class="image__title">Hollyrood Abbey</div>
                <p class="image__description">
                    January 26, 2019
                </p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="gallery-image col-sm">
            <img class="image__img" src="{% static 'st gallen.jpg' %}" alt="St. Gallen">
            <div class="image__overlay">
                <div class="image__title">St. Gallen</div>
                <p class="image__description">
                    January 28, 2019
                </p>
            </div>
        </div>
        <div class="gallery-image col-sm">
            <img class="image__img" src="{% static 'the five guys.jpg' %}" alt="Five Guys UK">
            <div class="image__overlay">
                <div class="image__title">Five Guys</div>
                <p class="image__description">
                    January 31, 2019
                </p>
            </div>
        </div>
        <div class="gallery-image col-sm">
            <img class="image__img" src="{% static 'here comes the sun.jpg' %}" alt="Hindia at Here Comes The Sun">
            <div class="image__overlay">
                <div class="image__title">Here Comes The Sun</div>
                <p class="image__description">
                    August 10, 2019
                </p>
            </div>
        </div>
    </div>
</div>
<br><br><br>
{% endblock content %}

templates/story4/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}MARTOUT{% endblock title %}

{% block content %}
<div class="section introduction container">
    <div class="row">
        <div class="logo col">
            <img class="mx-auto d-block" src="{% static 'LOGO-WEBSITE.png' %}" alt="Logo" height="75px" width="75px">
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h1 class="title">Hello!</h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <p>
                This website is created by Anthony Martin Hasurungan,
                a third year student majoring in Information Systems at
                Universitas Indonesia.
            </p>
        </div>
    </div>
</div>
<br><br>
<div class="bg-image">
    <img src="{% static 'john lennon-cropped.jpg' %}" alt="Picture of John Lennon">
</div>
<br><br><br>
<div class="section isi about-me container">
    <div class="row">
        <div class="text col">
            <h2>About Me</h2>
            <p>
                Anthony Martin H. is an easy-going
                and open-handed person. He also has high
                curiosity about everything and is eager to
                learn new things everyday. He is looking
                forward to improving his interpersonal skills
                and gaining work experience in the coming days.
            </p>
        </div>
    </div>
</div>
<br><br><br>
<div class="section isi interests container">
    <div class="row">
        <div class="picture col-lg-7 col-md-7 col-sm-7 col-7">
            <div class="short-div">
                <img class="img-fluid" src="https://www.fodors.com/wp-content/uploads/2019/06/06_HERO__TravelGear_anete-lusina-609863-unsplash.jpg" alt="Picture of a guy wandering in an airport">
            </div>
            <div class="short-div">
                <img class="img-fluid" src="https://pbs.twimg.com/media/EDeWIHSX4AAx91h.jpg" alt="Picture of The 1975 concert">
            </div>
            <div class="short-div">
                <img class="img-fluid" src="https://dvyvvujm9h0uq.cloudfront.net/com/articles/1543483387-reinhart-julian-1145947-unsplash.jpg" alt="Picture of a guy with a camera">
            </div>
            <div class="short-div">
                <img class="img-fluid" src="https://static.standard.co.uk/s3fs-public/thumbnails/image/2017/04/28/13/nintendoswitchmariokart.jpg?w968" alt="Picture of two people playing Nintendo Switch">
            </div>
        </div>
        <div class="text col-lg-5 col-md-5 col-sm-5 col-5">
            <h2>Interests</h2>
            <p>
                Due to the ongoing global pandemic of
                COVID-19, I can only do one of these
                sadly (guess which one!)
            </p>
        </div>
    </div>
</div>
<br><br><br>
{% endblock content %}

templates/story4/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}Profile - MARTOUT{% endblock title %}

{% block content %}
<div class="section top container">
    <div class="row">
        <div class="col">
            <h1 class="title">PROFILE</h1>
        </div>
    </div>
</div>
<br><br>
<div class="section isi bio container">
    <div class="row">
        <div class="text col">
            <h2>Bio</h2>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="my-pic logo-wrapper col-xl-6 col-lg-6 col-md-6">
            <img class="center-block" src="{% static 'borough market.jpg' %}" alt="Picture of Anthony Martin H.">
        </div>
        <div class="text col-xl-6 col-lg-6 col-md-6">
            <p>
                <br>
                <b>Full Name</b><br>
                Anthony Martin Hasurungan <br><br>
                <b>Place of Birth</b><br>
                Jakarta, Indonesia<br><br>
                <b>Date of Birth</b><br>
                March 17, 2000<br><br>
                <b>Current Address</b><br>
                Kav. Marinir, Blok AC No. 8, Pondok Kelapa,
                Jakarta Timur
            </p>
        </div>
    </div>
</div>
<br><br><br>
<div class="section isi education container">
    <div class="row">
        <div class="left text col-xl-5 col-md">
            <h2>Education</h2>
        </div>
        <div class="right text col-xl-7 col-md">
            <p>
                <b>Universitas Indonesia</b><br>
                Bachelor's degree, Information Systems<br>
                2018 - Present<br><br>
                <b>SMA Negeri 81 Jakarta</b><br>
                Senior High School, Natural Sciences<br>
                2015 - 2018<br><br>
                <b>SMPK 5 BPK Penabur</b><br>
                Junior High School<br>
                2012 - 2015
            </p>
        </div>
    </div>
</div>
<br><br><br>
<div class="section isi experience container">
    <div class="row">
        <div class="left text col-xl-5 col-md">
            <h2>Work Experience</h2>
        </div>
        <div class="right text col-xl-7 col-md">
            <p>
                <b>COMPFEST</b><br>
                HRD Staff of Equipment and Security<br>
                Feb 2020 - Present<br><br>
                Staff of Direct Marketing<br>
                Feb 2019 - Oct 2019<br><br>
                <b>OH Fasilkom UI</b><br>
                Staff of Equipment<br>
                Sep 2019 - Nov 2019<br><br>
                <b>Universitas Indonesia</b><br>
                Teaching Assistant for Discrete Mathematics 1<br>
                Sep 2019 - Dec 2019
            </p>
        </div>
    </div>
</div>
<br><br><br>
<div class="section isi skills container">
    <div class="row">
        <div class="left text col-xl-5 col-md">
            <h2>Skills</h2>
        </div>
        <div class="right text col-xl-7 col-md">
            <p>
                Microsoft Office<br>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <br><br>
                Java<br>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
                <br><br>
                Python<br>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <br><br>
                PostgreSQL<br>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
                <br><br>
                HTML5/CSS<br>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <br><br>
                Teamwork<br>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <br><br>
                Business<br>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <br><br>
                Problem-Solving<br>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
            </p>
        </div>
    </div>
</div>
<br><br><br><br>
<div class="section download container">
    <div class="row">
        <div class="col">
            <p>To know more about Anthony,
                you can download his resume by clicking
                the button below
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <a href="https://drive.google.com/file/d/1QRQNrAo_WuTn4N-YtM16v5OIIRslb0xD/view?usp=sharing">
                <img src="{% static 'download-button.png' %}" alt="Download Icon">
            </a>
        </div>
    </div>
</div>
<br><br><br><br>
{% endblock content %}

templates/story5/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Courses - MARTOUT{% endblock title %}

{% block content %}
<div class="container">
    <h1 class="title border-bottom">COURSES</h1>
    <div class="row my-5">
        <div class="col">
            <a href="{{ add_url }}">
                <button type="button" class="btn btn-dark col-2 mr-auto">Add Courses</button>
            </a>
        </div>
    </div>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show mt-4" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
    
    {% for course in courses %}
        <div class="card mt-3">
            <div class="card-body d-flex justify-content-between flex-column flex-md-row">
                <div>
                    <h5 class="card-title"><b>{{ course.name }} - {{ course.term }} {{ course.year }}</h5></a>
                    <h6 class="card-subtitle mb-2 text-muted">
                        Lecturer: {{ course.teacher }}<br>
                        Credit: {{ course.sks }} SKS<br>
                        Room: {{ course.room }}<br><br>
                        <i>{{ course.desc }}</i>
                    </h6>
                </div>
                <a href="{% url 'story5:delete' course.id %}" class="card-link text-danger mt-3 mt-md-0 mr-md-4 align-self-center">DELETE</a>
            </div>
        </div>
    {% endfor %}
</div>
<br><br><br>
{% endblock content %}

templates/story6/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Activities - MARTOUT{% endblock title %}

{% block content %}
<div class="container">
    <h1 class="title border-bottom">ACTIVITIES</h1>
    <Form method="POST" class="row my-5">
        {% csrf_token %}
        <div class="col-7 ml-auto">
            {{ activityForm.activity }}
        </div>
        <button type="submit" class="btn btn-dark col-2 mr-auto">
            Add Activity
        </button>
    </Form>
    <hr>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert dismissible fade show mt-4" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}
    <div class="d-flex justify-content-around flex-wrap pb-4">
        {% for activity in activities %}
        <div class="card bg-light mt-5" style="width: 18rem">
            <div class="card-header">
                <div class="row">
                    <h5 class="col-10 mb-2">{{ activity }}</h5>
                    <a href="{% url 'story6:activityDelete' activity.id %}" class="col-2">
                        <button type="button" class="close mb-2">&times;</button>
                    </a>
                </div>
            </div>
            <div class="card-body">
                <h6 class="card-title">Members:</h6>
                <p></p>
                <ul>
                    {% for member in members %}
                    {% if member.kegiatan.id == activity.id %}
                    <li class="row">
                        <h5 class="col-10"> {{ member }} </h5>
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
                <form method="POST">
                    {% csrf_token %}
                    {{ memberForm.member }}
                    <input name="kegiatan" type="text" value="{{ activity.id }}" style="display: none">
                    <button type="submit" class="btn btn-dark col-6 mt-2">Join</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<br><br><br>
{% endblock content %}